name: calorie_tracker_app
description: A Flutter calorie tracking application with AI food recognition.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Image handling and camera
  image_picker: ^1.0.7
  image: ^4.1.7                    # 图像处理核心库
  path_provider: ^2.1.2           # 文件路径管理
  shared_preferences: ^2.2.2      # 用户学习数据存储
  

  # Charts for visualization
  fl_chart: ^0.64.0

  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true