name: calorie_tracker_flutter
description: A comprehensive calorie tracking Flutter application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI and Charts
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.2
  
  # Image Processing (暂时移除 TensorFlow Lite)
  image: ^4.1.3
  image_picker: ^1.0.4
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/